* advent-of-code-2021-kotlin

Welcome to the Advent of Code Kotlin project created by [[https://github.com/kristinngodfrey][kristinngodfrey]] using the [[https://github.com/kotlin-hands-on/advent-of-code-kotlin-template][Advent of Code Kotlin Template]] delivered by JetBrains.

In this repository, kristinngodfrey is about to provide solutions for the puzzles using Kotlin language.

If you're stuck with Kotlin-specific questions or anything related to this template, check out the following resources:

- [[https://kotlinlang.org][Kotlin docs]]
- [[https://github.com/kotlin-hands-on/advent-of-code-kotlin-template/issues][Template issue tracker]]

** Description 
An annual event of Christmas-oriented programming challenges started December 2015.
Every year since then, beginning on the first day of December, a programming puzzle is published every day for twenty-four days.
You can solve the puzzle and provide an answer using the language of your choice.

** Contents

| Challenge          | File     |
|--------------------+----------|
| Day 1: Sonar Sweep | [[./src/Day01.kt][part 1-2]] |
| Day 2: Dive! | [[./src/Day21.kt][part 1-2]] |
